const videos = [
  {
    _id: "3teflb1QNN4",
    name: "What Can You Do Without a Brain?",
    creator: "Vsauce",
    date: "Oct 25, 2012",
    category: ["Science", "Learning"],
  },

  {
    _id: "1G4isv_Fylg",
    name: "Coldplay - Paradise (Official Video)",
    creator: "Coldplay",
    date: "Oct 19, 2011",
    category: ["Song", "Coldplay"],
  },
  {
    _id: "mAWZf96w2gs",
    name: "The Intersphere Man On The Moon Live @ Studio4",
    creator: "The Intersphere",
    date: "Dec 29, 2021",
    category: ["Song", "Intersphere"],
  },
  {
    _id: "Cz6NrW9eOgc",
    name: "Don't Think Twice",
    creator: "The Intersphere - Topic",
    date: "Nov 29, 2018",
    category: ["Song", "Intersphere"],
  },
  {
    _id: "hWhny7bAiT8",
    name: "Best of Stewie | Family Guy",
    creator: "EntertainMe | Best ofs",
    date: "Aug 10, 2021",
    category: ["FamilyGuy", "Comedy"],
  },
  {
    _id: "PCcYmfoi-KY",
    name: "Family Guy - Peter Looks For a Gang",
    creator: "Hippie Joe",
    date: "Nov 29, 2019",
    category: ["FamilyGuy", "Comedy"],
  },
  {
    _id: "IkDAb4hlof0",
    name: "Family Guy roasting every country",
    creator: "Peter Griffin",
    date: "Sep 29, 2020",
    category: ["FamilyGuy", "Comedy"],
  },
  {
    _id: "egEraZP9yXQ",
    name: "How Many Holes Does a Human Have?",
    creator: "Vsauce",
    date: "Feb 17, 2020",
    category: ["Science", "Learning"],
  },
  {
    _id: "mxhxL1LzKww",
    name: "How Much of the Earth Can You See at Once?",
    creator: "Vsauce",
    date: "Jul 17, 2017",
    category: ["Science", "Learning"],
  },
  {
    _id: "IJhgZBn-LHg",
    name: "How Earth Moves",
    creator: "Vsauce",
    date: "Jun 13, 2016",
    category: ["Science", "Learning"],
  },
  {
    _id: "PEikGKDVsCc",
    name: "Why Are Things Creepy?",
    creator: "Vsauce",
    date: "Jul 3, 2013",
    category: ["Science", "Psychology"],
  },
  {
    _id: "ky6lXtghdTg",
    name: "Maharashtrachi HasyaJatra - महाराष्ट्राची हास्यजत्रा - Ep 181 - Full Episode - 25th July, 2021",
    creator: "Sony Marathi",
    date: "Jul 27, 2021",
    category: ["Marathi", "Comedy"],
  },
  {
    _id: "gwnR9ECQcak",
    name: "Maharashtrachi Hasya Jatra - महाराष्ट्राची हास्यजत्रा - Ep - 170 - Full Episode - 24th June, 2021",
    creator: "Sony Marathi",
    date: "Jun 26, 2021",
    category: ["Marathi", "Comedy"],
  },
  {
    _id: "VFPKpZhU6CM",
    name: "महाराष्ट्राची हास्य जत्रा - नव्या कोऱ्या विनोदाचा पुन्हा नवा हंगाम - Episode 42 -22nd September 2020",
    creator: "Sony Marathi",
    date: "Sep 24, 2020",
    category: ["Marathi", "Comedy"],
  },
  {
    _id: "Jn09UdSb3aA",
    name: "The Best of Chopin",
    creator: "HALIDONMUSIC",
    date: "Mar 4, 2020",
    category: ["bestofchopin", "halidonmusic", "chopin"],
  },
  {
    _id: "ds07D9g8SAs",
    name: "Chopin - Relaxing Classical Piano",
    creator: "HALIDONMUSIC",
    date: "Feb 3, 2021",
    category: ["bestofchopin", "halidonmusic", "chopin"],
  },
];

export default videos;
